title: Below the Byte
description: Exploring systems, one byte at a time.
theme: minima

baseurl: "/below-the-byte"
url: "https://gurgi1970.github.io"

author:
  name: James
  bio: 10k HP Journey | Retro Dev | Curious Mind

markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

include:
  - _pages

header_pages:
  - _pages/about.md

collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_pages"
    values:
      layout: page
